object ProjectVersions {
    const val COMPILE_SDK = 29
    const val TARGET_SDK = 29
    const val MIN_SDK = 21

    const val APPCOMPAT = "1.1.0"
    const val CAMERA = "1.0.0-alpha06"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val COROUTINES = "1.3.2"
    const val DAGGER = "2.25.2"
    const val ESPRESSO_CORE = "3.2.0"
    const val FIREBASE_AUTH = "19.2.0"
    const val FIREBASE_CLOUD_MESSAGING = "20.0.1"
    const val FIREBASE_CORE = "17.2.1"
    const val FIREBASE_CRASHLYTICS = "2.10.1"
    const val FIREBASE_VISION = "24.0.1"
    const val FRAGMENT = "1.1.0"
    const val GLIDE = "4.9.0"
    const val JUNIT = "4.12"
    const val KOTLIN = "1.3.61"
    const val KTX = "1.1.0"
    const val LIFECYCLE = "2.1.0"
    const val MATERIAL = "1.2.0-alpha02"
    const val MAPBOX = "8.5.0"
    const val NAVIGATION = "2.1.0"
    const val OKHTTP = "4.2.1"
    const val QRGEN = "2.6.0"
    const val RETROFIT = "2.6.1"
    const val RETROFIT_SERIALIZATION = "0.4.0"
    const val SERIALIZATION = "0.11.0"
    const val SQLDELIGHT = "1.2.0"
    const val SWIPE_REFRESH = "1.0.0"
    const val TEST_JUNIT = "1.1.1"
    const val TEST_RULES = "1.2.0"
    const val THREE_TEN_ABP = "1.2.1"
}